language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  vim --version
  vim -Nu <(cat << VIMRC
  set nocompatible
  filetype off
  let g:vim_namespace_obj_map_keys = 1
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null
