language: vim

before_script: |
  git clone https://github.com/junegunn/vader.vim.git

script: |
  ls
  pwd
  vim -Nu <(cat << VIMRC
  filetype off
  set nocompatible
  set rtp+=vader.vim
  set rtp+=.
  filetype plugin indent on
  syntax enable
  VIMRC) -c 'Vader! test/*' > /dev/null
